//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MvcDbStokModel", "FK_Urunler_Kategoriler", "Kategoriler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcStok.Models.Entity.Kategoriler), "Urunler", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcStok.Models.Entity.Urunler), true)]
[assembly: EdmRelationshipAttribute("MvcDbStokModel", "FK_Satislar_Musteriler", "Musteriler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcStok.Models.Entity.Musteriler), "Satislar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcStok.Models.Entity.Satislar), true)]
[assembly: EdmRelationshipAttribute("MvcDbStokModel", "FK_Satislar_Urunler", "Urunler", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MvcStok.Models.Entity.Urunler), "Satislar", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcStok.Models.Entity.Satislar), true)]

#endregion

namespace MvcStok.Models.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MvcDbStokEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MvcDbStokEntities object using the connection string found in the 'MvcDbStokEntities' section of the application configuration file.
        /// </summary>
        public MvcDbStokEntities() : base("name=MvcDbStokEntities", "MvcDbStokEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MvcDbStokEntities object.
        /// </summary>
        public MvcDbStokEntities(string connectionString) : base(connectionString, "MvcDbStokEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MvcDbStokEntities object.
        /// </summary>
        public MvcDbStokEntities(EntityConnection connection) : base(connection, "MvcDbStokEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Kategoriler> Kategoriler
        {
            get
            {
                if ((_Kategoriler == null))
                {
                    _Kategoriler = base.CreateObjectSet<Kategoriler>("Kategoriler");
                }
                return _Kategoriler;
            }
        }
        private ObjectSet<Kategoriler> _Kategoriler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Musteriler> Musteriler
        {
            get
            {
                if ((_Musteriler == null))
                {
                    _Musteriler = base.CreateObjectSet<Musteriler>("Musteriler");
                }
                return _Musteriler;
            }
        }
        private ObjectSet<Musteriler> _Musteriler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Satislar> Satislar
        {
            get
            {
                if ((_Satislar == null))
                {
                    _Satislar = base.CreateObjectSet<Satislar>("Satislar");
                }
                return _Satislar;
            }
        }
        private ObjectSet<Satislar> _Satislar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Urunler> Urunler
        {
            get
            {
                if ((_Urunler == null))
                {
                    _Urunler = base.CreateObjectSet<Urunler>("Urunler");
                }
                return _Urunler;
            }
        }
        private ObjectSet<Urunler> _Urunler;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Kategoriler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKategoriler(Kategoriler kategoriler)
        {
            base.AddObject("Kategoriler", kategoriler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Musteriler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMusteriler(Musteriler musteriler)
        {
            base.AddObject("Musteriler", musteriler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Satislar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSatislar(Satislar satislar)
        {
            base.AddObject("Satislar", satislar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Urunler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrunler(Urunler urunler)
        {
            base.AddObject("Urunler", urunler);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcDbStokModel", Name="Kategoriler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Kategoriler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Kategoriler object.
        /// </summary>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        public static Kategoriler CreateKategoriler(global::System.Byte kategoriId)
        {
            Kategoriler kategoriler = new Kategoriler();
            kategoriler.KategoriId = kategoriId;
            return kategoriler;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                if (_KategoriId != value)
                {
                    OnKategoriIdChanging(value);
                    ReportPropertyChanging("KategoriId");
                    _KategoriId = StructuralObject.SetValidValue(value, "KategoriId");
                    ReportPropertyChanged("KategoriId");
                    OnKategoriIdChanged();
                }
            }
        }
        private global::System.Byte _KategoriId;
        partial void OnKategoriIdChanging(global::System.Byte value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KategoriAdi
        {
            get
            {
                return _KategoriAdi;
            }
            set
            {
                OnKategoriAdiChanging(value);
                ReportPropertyChanging("KategoriAdi");
                _KategoriAdi = StructuralObject.SetValidValue(value, true, "KategoriAdi");
                ReportPropertyChanged("KategoriAdi");
                OnKategoriAdiChanged();
            }
        }
        private global::System.String _KategoriAdi;
        partial void OnKategoriAdiChanging(global::System.String value);
        partial void OnKategoriAdiChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcDbStokModel", "FK_Urunler_Kategoriler", "Urunler")]
        public EntityCollection<Urunler> Urunler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Urunler>("MvcDbStokModel.FK_Urunler_Kategoriler", "Urunler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Urunler>("MvcDbStokModel.FK_Urunler_Kategoriler", "Urunler", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcDbStokModel", Name="Musteriler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Musteriler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Musteriler object.
        /// </summary>
        /// <param name="müsteriId">Initial value of the MüsteriId property.</param>
        public static Musteriler CreateMusteriler(global::System.Int32 müsteriId)
        {
            Musteriler musteriler = new Musteriler();
            musteriler.MüsteriId = müsteriId;
            return musteriler;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MüsteriId
        {
            get
            {
                return _MüsteriId;
            }
            set
            {
                if (_MüsteriId != value)
                {
                    OnMüsteriIdChanging(value);
                    ReportPropertyChanging("MüsteriId");
                    _MüsteriId = StructuralObject.SetValidValue(value, "MüsteriId");
                    ReportPropertyChanged("MüsteriId");
                    OnMüsteriIdChanged();
                }
            }
        }
        private global::System.Int32 _MüsteriId;
        partial void OnMüsteriIdChanging(global::System.Int32 value);
        partial void OnMüsteriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MusteriAD
        {
            get
            {
                return _MusteriAD;
            }
            set
            {
                OnMusteriADChanging(value);
                ReportPropertyChanging("MusteriAD");
                _MusteriAD = StructuralObject.SetValidValue(value, true, "MusteriAD");
                ReportPropertyChanged("MusteriAD");
                OnMusteriADChanged();
            }
        }
        private global::System.String _MusteriAD;
        partial void OnMusteriADChanging(global::System.String value);
        partial void OnMusteriADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MusteriSoyad
        {
            get
            {
                return _MusteriSoyad;
            }
            set
            {
                OnMusteriSoyadChanging(value);
                ReportPropertyChanging("MusteriSoyad");
                _MusteriSoyad = StructuralObject.SetValidValue(value, true, "MusteriSoyad");
                ReportPropertyChanged("MusteriSoyad");
                OnMusteriSoyadChanged();
            }
        }
        private global::System.String _MusteriSoyad;
        partial void OnMusteriSoyadChanging(global::System.String value);
        partial void OnMusteriSoyadChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcDbStokModel", "FK_Satislar_Musteriler", "Satislar")]
        public EntityCollection<Satislar> Satislar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Satislar>("MvcDbStokModel.FK_Satislar_Musteriler", "Satislar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Satislar>("MvcDbStokModel.FK_Satislar_Musteriler", "Satislar", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcDbStokModel", Name="Satislar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Satislar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Satislar object.
        /// </summary>
        /// <param name="satisId">Initial value of the SatisId property.</param>
        public static Satislar CreateSatislar(global::System.Int32 satisId)
        {
            Satislar satislar = new Satislar();
            satislar.SatisId = satisId;
            return satislar;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SatisId
        {
            get
            {
                return _SatisId;
            }
            set
            {
                if (_SatisId != value)
                {
                    OnSatisIdChanging(value);
                    ReportPropertyChanging("SatisId");
                    _SatisId = StructuralObject.SetValidValue(value, "SatisId");
                    ReportPropertyChanged("SatisId");
                    OnSatisIdChanged();
                }
            }
        }
        private global::System.Int32 _SatisId;
        partial void OnSatisIdChanging(global::System.Int32 value);
        partial void OnSatisIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Urunıd
        {
            get
            {
                return _Urunıd;
            }
            set
            {
                OnUrunıdChanging(value);
                ReportPropertyChanging("Urunıd");
                _Urunıd = StructuralObject.SetValidValue(value, "Urunıd");
                ReportPropertyChanged("Urunıd");
                OnUrunıdChanged();
            }
        }
        private Nullable<global::System.Int32> _Urunıd;
        partial void OnUrunıdChanging(Nullable<global::System.Int32> value);
        partial void OnUrunıdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MüsteriId
        {
            get
            {
                return _MüsteriId;
            }
            set
            {
                OnMüsteriIdChanging(value);
                ReportPropertyChanging("MüsteriId");
                _MüsteriId = StructuralObject.SetValidValue(value, "MüsteriId");
                ReportPropertyChanged("MüsteriId");
                OnMüsteriIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MüsteriId;
        partial void OnMüsteriIdChanging(Nullable<global::System.Int32> value);
        partial void OnMüsteriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ADET
        {
            get
            {
                return _ADET;
            }
            set
            {
                OnADETChanging(value);
                ReportPropertyChanging("ADET");
                _ADET = StructuralObject.SetValidValue(value, "ADET");
                ReportPropertyChanged("ADET");
                OnADETChanged();
            }
        }
        private Nullable<global::System.Int16> _ADET;
        partial void OnADETChanging(Nullable<global::System.Int16> value);
        partial void OnADETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Fiyat
        {
            get
            {
                return _Fiyat;
            }
            set
            {
                OnFiyatChanging(value);
                ReportPropertyChanging("Fiyat");
                _Fiyat = StructuralObject.SetValidValue(value, "Fiyat");
                ReportPropertyChanged("Fiyat");
                OnFiyatChanged();
            }
        }
        private Nullable<global::System.Decimal> _Fiyat;
        partial void OnFiyatChanging(Nullable<global::System.Decimal> value);
        partial void OnFiyatChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcDbStokModel", "FK_Satislar_Musteriler", "Musteriler")]
        public Musteriler Musteriler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musteriler>("MvcDbStokModel.FK_Satislar_Musteriler", "Musteriler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musteriler>("MvcDbStokModel.FK_Satislar_Musteriler", "Musteriler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Musteriler> MusterilerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Musteriler>("MvcDbStokModel.FK_Satislar_Musteriler", "Musteriler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Musteriler>("MvcDbStokModel.FK_Satislar_Musteriler", "Musteriler", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcDbStokModel", "FK_Satislar_Urunler", "Urunler")]
        public Urunler Urunler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urunler>("MvcDbStokModel.FK_Satislar_Urunler", "Urunler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urunler>("MvcDbStokModel.FK_Satislar_Urunler", "Urunler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Urunler> UrunlerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Urunler>("MvcDbStokModel.FK_Satislar_Urunler", "Urunler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Urunler>("MvcDbStokModel.FK_Satislar_Urunler", "Urunler", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcDbStokModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcDbStokModel", Name="Urunler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Urunler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Urunler object.
        /// </summary>
        /// <param name="urunId">Initial value of the UrunId property.</param>
        public static Urunler CreateUrunler(global::System.Int32 urunId)
        {
            Urunler urunler = new Urunler();
            urunler.UrunId = urunId;
            return urunler;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UrunId
        {
            get
            {
                return _UrunId;
            }
            set
            {
                if (_UrunId != value)
                {
                    OnUrunIdChanging(value);
                    ReportPropertyChanging("UrunId");
                    _UrunId = StructuralObject.SetValidValue(value, "UrunId");
                    ReportPropertyChanged("UrunId");
                    OnUrunIdChanged();
                }
            }
        }
        private global::System.Int32 _UrunId;
        partial void OnUrunIdChanging(global::System.Int32 value);
        partial void OnUrunIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Urunadi
        {
            get
            {
                return _Urunadi;
            }
            set
            {
                OnUrunadiChanging(value);
                ReportPropertyChanging("Urunadi");
                _Urunadi = StructuralObject.SetValidValue(value, true, "Urunadi");
                ReportPropertyChanged("Urunadi");
                OnUrunadiChanged();
            }
        }
        private global::System.String _Urunadi;
        partial void OnUrunadiChanging(global::System.String value);
        partial void OnUrunadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Marka
        {
            get
            {
                return _Marka;
            }
            set
            {
                OnMarkaChanging(value);
                ReportPropertyChanging("Marka");
                _Marka = StructuralObject.SetValidValue(value, true, "Marka");
                ReportPropertyChanged("Marka");
                OnMarkaChanged();
            }
        }
        private global::System.String _Marka;
        partial void OnMarkaChanging(global::System.String value);
        partial void OnMarkaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> UrunKategori
        {
            get
            {
                return _UrunKategori;
            }
            set
            {
                OnUrunKategoriChanging(value);
                ReportPropertyChanging("UrunKategori");
                _UrunKategori = StructuralObject.SetValidValue(value, "UrunKategori");
                ReportPropertyChanged("UrunKategori");
                OnUrunKategoriChanged();
            }
        }
        private Nullable<global::System.Byte> _UrunKategori;
        partial void OnUrunKategoriChanging(Nullable<global::System.Byte> value);
        partial void OnUrunKategoriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Urunstok
        {
            get
            {
                return _Urunstok;
            }
            set
            {
                OnUrunstokChanging(value);
                ReportPropertyChanging("Urunstok");
                _Urunstok = StructuralObject.SetValidValue(value, "Urunstok");
                ReportPropertyChanged("Urunstok");
                OnUrunstokChanged();
            }
        }
        private Nullable<global::System.Int32> _Urunstok;
        partial void OnUrunstokChanging(Nullable<global::System.Int32> value);
        partial void OnUrunstokChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> UrunFiyat
        {
            get
            {
                return _UrunFiyat;
            }
            set
            {
                OnUrunFiyatChanging(value);
                ReportPropertyChanging("UrunFiyat");
                _UrunFiyat = StructuralObject.SetValidValue(value, "UrunFiyat");
                ReportPropertyChanged("UrunFiyat");
                OnUrunFiyatChanged();
            }
        }
        private Nullable<global::System.Decimal> _UrunFiyat;
        partial void OnUrunFiyatChanging(Nullable<global::System.Decimal> value);
        partial void OnUrunFiyatChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcDbStokModel", "FK_Urunler_Kategoriler", "Kategoriler")]
        public Kategoriler Kategoriler
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategoriler>("MvcDbStokModel.FK_Urunler_Kategoriler", "Kategoriler").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategoriler>("MvcDbStokModel.FK_Urunler_Kategoriler", "Kategoriler").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Kategoriler> KategorilerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Kategoriler>("MvcDbStokModel.FK_Urunler_Kategoriler", "Kategoriler");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Kategoriler>("MvcDbStokModel.FK_Urunler_Kategoriler", "Kategoriler", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcDbStokModel", "FK_Satislar_Urunler", "Satislar")]
        public EntityCollection<Satislar> Satislar
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Satislar>("MvcDbStokModel.FK_Satislar_Urunler", "Satislar");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Satislar>("MvcDbStokModel.FK_Satislar_Urunler", "Satislar", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
